language: ruby
cache: bundler

rvm:
  - 2.5.3

services:
  - docker

env:
  global:
    - secure: "kJU6pvlcoKQnk/obAHdYeTiyBTRBU2q/e+9uigN43naehj7DQ8UAol5nxF/To9RtgGXoaBtH8l86JVnrKuf8mDy1ioKNROIzsr7blGLMK/c8JeJmITaEWLal9i3xTrwFWw+xSXBhcDj0qNEuKve/1+pC0MzjicLfV95FaT2O0e3/W15kIV3UEspwmm2Tn+galng6tCBFlYU7KpgFAE8eoC3VPJvpMLGjcUh3KS1VurGxoTRSksu/HnuYSXBg39MhmI1c3vP5tlnFt7Hh8sfVUdJGtyf8FsSFGXSVLwHi4/XbdzzsA60xgttDjx89uyKEXGuYgwxIUXLiyqDO3nfCfGR4Z/2Xkt45HtMt1IURpQ5HkijpNT/MH6hCeB8uJ1oSkszNFgXja/fmrQZf8N3cENo4kGNqwcMeZ2r4u9RQmrbD1pWsgfWcu/lGuidIsp0afCRywQOgvyojDT1/L54erWmnyOmBSecAoxhrF05TPmU4QKwqZfVAhydF30MeHp365DN/FTrDb2XLbxIDbamTJ0Quy4WM0VgGR1GnmPVIuBFUFoVG4FaBm4JzuGpLEcMhkvs9MHsE+P+gEKF7b50/Niy+b4q082KKkVnH7d1gTXYR79qnyLexe164h1SDreiVzzgBhSdWGwkBU05uTxKIffLTXFF67DkxqjFQBS+fkMc=" #DOCKER_USER
    - secure: "JmymmN4VAx1cM99SnGmIxSdVM5OyUnp3n6lVd2iYqCct4qwG/Qq3g25wGZdm8qYiVwE0dRHjJkUxtrK5Tl2tAkx1lJgThmOJlEHTBKfsy62kj5DzFGb7yxYk/smi0M5zg6zctuQsifs4RBhslT/w4JYqsTzI4EdNCilDrv0etMlse74mnWrxQl+4MjE2IWN/84aqLESF+Sm3TVBn0c5ABzVTHrQlvUFYAEsf2f3CGScnZSNvddZxkBiCA9FZls9bT8tqOWV22GxIQOywIV99nWGIg5tVVyd/82wnhA1HBoVtK2va1fzRTrQjIpCIHpvrJSQdy8DJ6jzH53pe/ZfGaf9gGDowEm09lITodN3OPYkykF27qLQQkrEP98fcPKx4CW7nQQa9nNU7JAnNLUMXY25DY8HsNpCCtkl1ELvh4QbZ9BENPXmRLpdgUNVFz3RnhWr6z8RNfKCnq5Z/47itrbeB4E+haQf24vrzYUnK6EKldXvUBxh0i4wFeJ/v+I1OZZ/ZCU4wEvstsuSUhRJ7rHt9TVDCl5AvFdB3NUMGQgXcItVycziNjoFwkLdEcN+2PxawGiycGlPdBYRBrtAQyoLVObSoWTCU6V2yZRmN7rxxUDBir2koFt8CQh7GO2pt8l5ZFrltd3NlhHIeNanRAYE2e3abiFw6Qyb0bE52xHs=" #DOCKER_PASS


script: false

jobs:
  include:   
    - stage: "Docker Build"
      script: bash ./docker/docker_push.sh
      name: "Deployment Builds"
      install: skip
      env:
      - REPO=salborough/slate
      - DOCKERFILE=./Dockerfile
      - WD=./

