language: ruby
cache: bundler

rvm:
  - 2.5.3

services:
  - docker

env:
  global:
    - secure: "FIJmU7VSR4HIRMxuHoal8CPg6EGlY+U7LlVL1A38I35t6upooZnbRCsol0fUO0Qnk8EjenuFZjeHqo99gwyVAP3/z2T4/YbeznN63nRwYuXMptwndsxzyay/E+t+sp/Jd8lqjFmSsXlytRui1tNUrhaEwnokCuvvRdzRqNxcKGf1eGWfbZcWq0I/BD9ahWHetJNDvrfWu3L1DI05aR7UTglvSrl/6YaeWEM3dqnld8L7eynIF/F7ArxpRtdvMicqJmT991xI5KJknalE4u8YFfCwD26Gt1zBNf87F5g+lNVCucwYesT/0o7l+oBa7WUoXV+RWlPE9wq8K4hKBHZ8nWWIeqZkwODHpooiNj8y9mp/HqpGgGjapAGlAlwXwEmIHIr/TWyd2Psuz7bLGLtHVqhrv4b183xiO90xm5m0KLNrUkT8kTFO6whHQfR7I44STvenHuQrPf2gAMu87MHaasdApTv6yzOxkKTxBd9juGlPBP7jJcGMRCrxnVBY7Y4k4Qz+aRlDRiSIlzX9jojIJ/2Jatn4HsdB6DPZ3ijMjqPHEB4W524vMKmAKfuB3LrWPbpV1kqkro7Nmv2KTG5gOXY/pe4e99JleplBeElFqG0Vo9InboaRo7duxGFWAuwNRPFMLd8DaNhtneV6vPG4n2yAGO0PodzLtaGz8xeRvvU=" #DOCKER_USER
    - secure: "P9cvquwaU8v/oX0WyrbHJQrXZnEu3Q5i9+5MKXJZ5vGZtltbQbSgjUCyjzozXi0pnhiWGbZJ9VJ1GR/FNJ6UmDTzc642JNk6bmYWxXgt9xNYZEB6/zbQZWtjCXhE2hbU6ki/x76mqcQ4bvRUmV+Q1I/a1Ew5Llv3XVV1hcvIVgVM2JuyYJMRpAs3Z5FZqIHlYKOybHTgdTbsUiJ5eTgKhuJbR8ND6mrAGD+NEw4LH36QT/uJFoBdXWwzDQ1qTMF888oPZHxP+pUQKImmF1wofY0IEvTC98ZahDcUfVwcbKY6j9rkXwjthjinrRe46WVz25rcG5Slr8KM02OLoBkE5KycIH7BBIPACGt6QSbvGXPZr208PJZ/1znJhKJz8Rc3I8YttXoR4/7pALF6ing4HcIuT9XbjucfyBAxcu7sSiESspyJ2w1A1488cmJtJIYmMzrfP6433JzLX5CbpL+0Ip3w9T142qZCvzcEq2LfafBJ6vX3Kgufib6jQtZcBaWMBFSWBYd6/AUVenNeWj4JRpK1pAAbZtt0QkbZ+HwSgr/ZqOyDLgoN2sSJGM8/UIDPJYVj8bmhRyrE258hgP+PjOkH7TJ02z52603AoeJjReShhijjc5vF8U9VB9pLu2hsZB3c+4tuD7MEWCI58O/BygAXMHPBCjRnsmc9s8Lqvrs=" #DOCKER_PASS


script: false

jobs:
  include:   
    - stage: "Docker Build"
      script: bash ./docker/docker_push.sh
      name: "Deployment Builds"
      install: skip
      env:
      - REPO=salborough/slate
      - DOCKERFILE=./Dockerfile
      - WD=./

